trigger:
  batch: false

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'Test') }}:
    stageName: test
  ${{ elseif eq(variables['Build.SourceBranchName'], 'main') }}:
    stageName: prod
  ${{ else }}:
    stageName: dev

jobs:
- job:
  steps:
    - task: AzureCLI@2
      displayName: Connect to container registry
      inputs:
        azureSubscription: $(ContainerRegistryConnectionName)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ContainerRegistryName) --expose-token
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName-${{variables.stageName}})
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --location westeurope \
            --template-file $(Build.sourcesdirectory)/IaC/*.bicep \
            --parameters $(Build.sourcesdirectory)/IaC/parameters.${{variables.stageName}}.json \